//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     DSS Runtime Version: 2.0.730.3
//     CLR Runtime Version: 2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using W3C.Soap;
using ajmessagesdssservices = Robotics.AjMessagesDssServices;


namespace Robotics.AjMessagesDssServices.Controller
{
    
    
    /// <summary>
    /// AjMessage ServiceNode Contract class
    /// </summary>
    public sealed class Contract
    {
        
        /// <summary>
        /// The Dss Service contract
        /// </summary>
        [DataMember()]
        public const String Identifier = "http://schemas.tempuri.org/2008/05/ajmessages/controller.html";
    }
    
    /// <summary>
    /// The ServiceNode State
    /// </summary>
    [DataContract()]
    public class ControllerServiceState
    {
    }

    [DataContract()]
    public class ProcessMessageRequest
    {
        [DataMember()]
        public string Action;

        [DataMember()]
        public string Body;
    }

    /// <summary>
    /// ServiceNode Main Operations Port
    /// </summary>
    [ServicePort()]
    public class ControllerServiceOperations : PortSet<DsspDefaultLookup, DsspDefaultDrop, Get, ProcessMessage>
    {
    }
    
    /// <summary>
    /// AjMessagesDssServices Get Operation
    /// </summary>
    public class Get : Get<GetRequestType, PortSet<ControllerServiceState, Fault>>
    {
        
        /// <summary>
        /// AjMessagesDssServices Get Operation
        /// </summary>
        public Get()
        {
        }
        
        /// <summary>
        /// AjMessagesDssServices Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
                base(body)
        {
        }
        
        /// <summary>
        /// AjMessagesDssServices Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, Microsoft.Ccr.Core.PortSet<ControllerServiceState,W3C.Soap.Fault> responsePort) : 
                base(body, responsePort)
        {
        }
    }

    public class ProcessMessage : Insert<ProcessMessageRequest, PortSet<DefaultInsertResponseType, Fault>>
    {
        public ProcessMessage()
        {
        }

        public ProcessMessage(ProcessMessageRequest body)
            : base(body)
        {
        }

        public ProcessMessage(ProcessMessageRequest body, PortSet<DefaultInsertResponseType, Fault> responseport)
            : base(body, responseport)
        {
        }
    }

}
